name: todo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  rxdart: ^0.27.2
  share_plus: ^6.3.0
  sqflite: ^2.2.2
  timezone: ^0.9.1
  url_launcher: ^6.1.7


dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
    - images/logo.png
    - images/gitlogo.png
    - images/fblogo.png
    - images/emaillogo.png
